### ISSUE TITLE
Css should be moved to own files to support older Umb versions

### ISSUE THREAD

**Issue by nhaberl** [KOBENDigital/Iconic#2]
Does it work with lower version of Umbraco like 7.3 also ?

**Comment by skartknet** [comment]
It should, but I haven't had time to test it.

**Comment by nhaberl** [comment]
OK thanks

**Comment by skartknet** [comment]
I tested it with 7.3 and there are some issues with the CSS. I'll fix them soon.

**Comment by skartknet** [comment]
I tried to adapt the package to work with v7.3 but it's not only CSS what has to change. Some directives used are only available since 7.6. I pushed the changes I did for the configuration screen to a new branch called _comp73_ but I'm not going to continue with it. If someone wants to do the job, that branch is a good starting point.
